/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 f1car2.glb --transform
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

export function Model(props) {
    const frontTiresRef = useRef();
    const backTiresRef = useRef();
    const rimFrontRef = useRef();
    const rimBckRef = useRef();

    useFrame(({clock}) => {
        const speedKmph = 250;
        const circumferenceInches = 18;
        // Convert speed from km/h to m/min
        const speedMpm = speedKmph * 1000 / 60;

        // Convert circumference from inches to meters
        const circumferenceMeters = circumferenceInches * 0.0254;


        // Calculate RPM
        const rpm = speedMpm / circumferenceMeters;
        const rotationPerSecond = (rpm * 2 * Math.PI) / 60; // Convert RPM to rad/s
        const rotationValue = clock.getElapsedTime() * rotationPerSecond;

        if (frontTiresRef.current) {
            frontTiresRef.current.rotation.x = rotationValue;
        }

        if (backTiresRef.current) {
            backTiresRef.current.rotation.x = rotationValue;
        }

        if (rimFrontRef.current) {
            rimFrontRef.current.rotation.x = rotationValue;
        }

        if (rimBckRef.current) {
            rimBckRef.current.rotation.x = rotationValue;
        }
    });

    const {nodes, materials} = useGLTF('models/f1car2-transformed.glb')


    return (<group {...props} dispose={null}>
        <mesh geometry={nodes.Spoiler_Front.geometry} material={materials.Spoiler_Ana}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Canard.geometry} material={materials.Kanard} position={[0, 0, 0.001]}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Front_Spoiler_Holder.geometry} material={materials.Torus_001}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Swan_Neck.geometry} material={materials.Swan_Neck} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Spoiler.geometry} material={materials.Spoiler} position={[0, 0.755, -5.057]}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Spoiler_Small.geometry} material={materials.Spoiler_Kucuk_1}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Spoiler_Big.geometry} material={materials.Spoiler_Kucuk_2}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Spoiler_DRS.geometry} material={materials.Spoiler_DRS_Pistonu}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Vertical_Radar_Wing.geometry} material={materials.Dikey_Kanat}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Small_Radar_Wing.geometry} material={materials.Kucuk_Kanat}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Horizontal_Radar_Wing.geometry} material={materials.Yatay_Kanat}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Horizontal_Radar_wing_2.geometry} material={materials.Yatay_Kanatlar}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Pitot_Tube_Wing.geometry} material={materials.Dikey_Kanat_001}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes['1'].geometry} material={materials.C_Karbon} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes['7'].geometry} material={materials.Düz_Karbon_2} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes['6'].geometry} material={materials.Cylinder_008} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Differential.geometry} material={materials.Difransiyel} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Chassis.geometry} material={materials.Şasi} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes['2'].geometry} material={materials.Cylinder} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Exhaust.geometry} material={materials.Egzos} position={[0, 0, 0.177]}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes['3'].geometry} material={materials.Cylinder_001} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes['4'].geometry} material={materials.Cylinder_005} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes['5'].geometry} material={materials.Cylinder_006} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Front_Disk.geometry} material={materials.Ön_Disk} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Control.geometry} material={materials.Direksiyon} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Switch.geometry} material={materials.Cube} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Shifter.geometry} material={materials.Kulaklar} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Control_Shaft.geometry} material={materials.Direksiyon_Mili}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Bujon_Back_Whell.geometry} material={materials.Bujon}
              position={[1.967, -0.353, -3.871]}/>
        <mesh ref={rimBckRef} geometry={nodes.Rim_Bck.geometry} material={materials.Jant} position={[2.039, -0.332, -3.878]}/>
        <mesh ref={backTiresRef} geometry={nodes.Back_Tires.geometry} material={materials.Lastik} position={[1.601, -0.353, -3.871]}/>
        <mesh geometry={nodes.Inside_Rim_Back.geometry} material={materials.İç_Jant}
              position={[1.955, -0.353, -3.871]}/>
        <mesh geometry={nodes.Tires_Lid_Back.geometry} material={materials.Lastik_Kapağı}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Bujon_Front_Wheel.geometry} material={materials.Bujon_001}
              position={[2.005, -0.353, 3.322]}/>
        <mesh ref={rimFrontRef} geometry={nodes.Rim_Front.geometry} material={materials.Jant_001} position={[2.074, -0.332, 3.316]}/>
        <mesh ref={frontTiresRef} geometry={nodes.Front_Tires.geometry} material={materials.Lastik_001}
              position={[1.714, -0.353, 3.322]}/>
        <mesh geometry={nodes.Tires_Lid_Front.geometry} material={materials.Lastik_Kapağı_001}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Inside_Rim_Front.geometry} material={materials.İç_Jant_001}
              position={[2.005, -0.353, 3.322]}/>
        <mesh geometry={nodes.Small_Tube.geometry} material={materials.Kısa_Çubuk} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Mirror.geometry} material={materials.Ayna} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.DOWN_CANARD.geometry} material={materials.Alt_Kanard} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Grid.geometry} material={materials.Izgaralar} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Cabin.geometry} material={materials.Kabin} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Body.geometry} material={materials.Govde} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Front_Wing.geometry} material={materials.Ön_Kanatlar} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Body_Back_Wing.geometry} material={materials.Govde_001} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Belt_Lock.geometry} material={materials.Kilit} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Shoulder_Belt.geometry} material={materials.Omuz_Kemeri}
              rotation={[Math.PI / 2, 0, 0]} scale={0.01}/>
        <mesh geometry={nodes.Waist_Belt.geometry} material={materials.Bel_Kemeri} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Seat.geometry} material={materials.Koltuk} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Clip1.geometry} material={materials.Toka} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Clip2.geometry} material={materials.Toka_001} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Clip3.geometry} material={materials.Toka_002} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Leg_Belt.geometry} material={materials.Bacak_Kemeri} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Lights.geometry} material={materials.Lights} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
        <mesh geometry={nodes.Mirror_Glass.geometry} material={materials.Ayna_Camı} rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}/>
    </group>)
}

useGLTF.preload('models/f1car2-transformed.glb')
